name: Backend Deploy

on:
  repository_dispatch:
    types:
      - deploy-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Download frontend build artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-build

      - name: Copy frontend build to backend public directory
        run: cp -R dist/ mc-player-admin/service/public/

      - name: Install dependencies
        run: yarn install

      - name: Start backend server
        run: yarn start
